### ISSUE TITLE
error in content type fixer

### ISSUE THREAD

**Issue by tortino** [jscher2000/Content-Type-Fixer-extension#10]
Hello,
I'm using your extension Content-Type Fixer version 1.7.2, on firefox 88.0.1 and Windows10.

I sometimes get a strange error: I load a page and it is shown a popup asking to save an html file.
It seems random, sometimes the page loads correctly (without save dialog) and sometimes it doesn't (it shows save dialog).

See these screenshots:

![immagine](https://user-images.githubusercontent.com/26486758/118388442-c8456100-b624-11eb-84f3-daadc24b2804.png)

![immagine](https://user-images.githubusercontent.com/26486758/118388444-cda2ab80-b624-11eb-98c4-6c1c3611e446.png)

And these are the options I set in the extension:

![immagine](https://user-images.githubusercontent.com/26486758/118388451-dabf9a80-b624-11eb-9b02-0d46bbcecb0e.png)

**Comment by jscher2000** [comment]
Hmm, I don't know why that is happening. Could you check the Log (click Add/Edit Content Types (View Log)) and see what is listed for that request. Normally for HTML it would just say something along the following lines:

    C-T: No Action - no association for extension; current CT is "text/html; charset=utf-8"

For files forced to download, it usually looks more like this:

    C-T: No Action - CT already set to "application/pdf"
    C-D: Forced to attachment

But you have kept the default exception for HTML so I wonder if the Content-Type is written in a way the extension is not parsing correctly. Thanks.

**Comment by tortino** [comment]
Hi, thank for your reply.
I looked into the log and found this:

![immagine](https://user-images.githubusercontent.com/26486758/119226364-f89b6c80-bb08-11eb-9175-e687dfefd895.png)

**Comment by jscher2000** [comment]
Uh-oh, the extension modified a redirect. I didn't realize that was a possibility. Let me try disabling that.

**Comment by jscher2000** [comment]
Actually, I misread that. 304 is a code returned when Firefox is checking the freshness of a cached file and the server is indicating that it's okay to use the cached file. But either way, the problem is that the server isn't indicating the content type is text/html so the exception for HTML pages is not working.

I'm uploading version 1.7.3 which will limit content disposition changes to responses with the status code 200. Hopefully that won't break anyone's workflow, but I guess I'll find out!

**Comment by tortino** [comment]
thank you for the updated release. 
I installed it and I'll report back here if my issue is fixed.

**Comment by tortino** [comment]
hello, my issue seems fixed. thank you.
