### ISSUE TITLE
No "Open with firefox" option downloading a PDF file

### ISSUE THREAD

**Issue by hopalongrock** [jscher2000/Content-Type-Fixer-extension#16]
There is no "Open with Firefox" option for a PDF file from a specific site, only "Open With Adobe Acrobat Reader" and "Save file".
Firefox contains for "Portable Document Format (PDF)" Content type the "Always ask" action.

I have to set the action to "Open with Firefox" to view the PDF in Firefox.

For other downloads the "Open with Firefox" option exists!

This happens with content-type fixer too, using it's default settings.

In case of download, the file has a generated name, for example BrrGhM8s.pdf

Microsoft Edge shows the file immediately (the default for PDF is Adobe Acrobat Reader)

I attached the log, but I don't know, what can I do, I don't see PDF extension, and only the svg extension entry has Add button.

It's a personal download, the site is password protected.

I hope you can help,

Thanks

![JAV Log of Recent Requests 20230327](https://user-images.githubusercontent.com/6840865/227942103-34c269c2-b194-48a9-80b1-586fc65c25a3.jpg)

**Comment by jscher2000** [comment]
I think this is a duplicate issue. See #17.
