### ISSUE TITLE
Request: Indicate to server no support for WebP (exceptions for popular websites that rely on it)

### ISSUE THREAD

**Issue by Nicholas-Steel** [jscher2000/Content-Type-Fixer-extension#18]
Hi, it would be fantastic if there was a setting to prevent the web browser from telling websites it supports WebP so that websites are more likely to deliver files in their original format (Gif, JPG etc).

**Comment by jscher2000** [comment]
Hi, I have a separate extension for that: https://addons.mozilla.org/firefox/addon/dont-accept-webp/

**Comment by Nicholas-Steel** [comment]
Awesome, thanks!
