### ISSUE TITLE
Some preferences are not getting saved

### ISSUE THREAD

**Issue by rampaa** [jscher2000/Content-Type-Fixer-extension#5]
Steps to produce:
1) Enable/Disable Content Types
2) Disable 7z
3) Restart Firefox
7z will be enabled when the Firefox restarted. But I would like my preferences to be saved.

I am using Firefox 75 64-bit.

**Comment by jscher2000** [comment]
Whoops, I see the problem. Line 427 of the background script updates the enabled/disabled status of user-added content-type overrides, but there's a line missing to handle built-in content-type overrides. Definitely need to fix that!!

**Comment by jscher2000** [comment]
So finally I fixed this today in version 1.6. Thank you for reporting it.

**Comment by jscher2000** [comment]
Bah, I thought I fixed it, but it's still not right.

**Comment by jscher2000** [comment]
When you re-enable the type (for example PDF) it remains marked as a custom type, which isn't helpful, but I'm going to let that slide for a while because I plan to completely revamp the UI in version 2.0.
