### ISSUE TITLE
Extension interfering - how to fix?

### ISSUE THREAD

**Issue by siffegh** [jscher2000/Content-Type-Fixer-extension#8]
At https://www.softwareok.com/?Download=GetWindowText, click either of the two GetWindowText zip links.  There's a prompt to save, but the filenames are always randomchars. zip (e.g., Op2Ygv0a.zip), and the downloaded files are marked as corrupted. Disabling the extension fixes it. Is there a built-in workaround/solution for this?

**Comment by jscher2000** [comment]
Hmm, I see the problem. The link opens a download page:

https://www.softwareok.com/?Download=GetWindowText&goto=../Download/GetWindowText_x64.zip

The extension sees the .zip on the end and flips the content type from HTML to ZIP.

So I need to avoid "correcting" text/html to another content type.

**Comment by jscher2000** [comment]
I just posted version 1.7 to address this, testing on that site. If you see a similar problem elsewhere, let me know.

**Comment by siffegh** [comment]
Thanks, looks good!
