### ISSUE TITLE
Can't download PDFs from Google Docs

### ISSUE THREAD

**Issue by Elaborendum** [jscher2000/Content-Type-Fixer-extension#9]
When the extension is active, its not possible to download PDFs out of Google Docs files.

**Comment by Elaborendum** [comment]
Just tried downloading from Documents, Presentations and Spreadsheets and got the following, respectively.

- doc-0c-c0-docstext.googleusercontent.com
- doc-0g-08-slides.googleusercontent.com
- doc-0k-10-sheets.googleusercontent.com

So, googleusercontent.com. This appears in the log:
![image](https://user-images.githubusercontent.com/71190696/117895799-beb6a480-b284-11eb-85cd-014158aed2b9.png)

Just in case, there are also grey lines that all come from docs.google.com and just say 
![image](https://user-images.githubusercontent.com/71190696/117895921-0f2e0200-b285-11eb-9c77-c311d3686950.png)

**Comment by jscher2000** [comment]
Oh... the exception only applied on mail.google.com and drive.google.com, and it never occurred to me to test downloading as PDF.

I have added docs.google.com in version 1.7.2 and it seems to resolve the issue.

**Comment by Elaborendum** [comment]
Thank you, it is fixed.
